[project]
name = "nyc-taxi"
version = "0.1.0"
requires-python = "==3.11.*"
dependencies = []

[dependency-groups]
spark = ["pyspark==3.5.6"]
dev = ["pytest>=8", "ruff"]

[tool.uv]
package = false
default-groups = ["dev", "spark"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
